### ISSUE TITLE
Option to search for devices in a directory

### ISSUE THREAD

**Issue by rwanyoike** [dasJ/sd-zfs#18]
This idea comes from the [ZFS ArchWiki recommendation](https://wiki.archlinux.org/index.php/ZFS#Importing_a_pool_created_by_id) against importing pools using `/dev/sd?` and https://github.com/zfsonlinux/zfs/wiki/FAQ#selecting-dev-names-when-creating-a-pool.

The `zfs` mkinitcpio hook on Archlinux for example has:

```
To search for devices in a directory other than "/dev":

        zfs_import_dir=/dev/disk/by-uuid
            or
        zfs_import_dir=/dev/disk/by-partuuid
            or
        zfs_import_dir=/dev/disk/by-path
            etc.
```

**Comment by dasJ** [comment]
ZFS searches the devices recursively, I use `/dev/mapper` paths. So I don't think there is any reason to specify the directory.
